name: Missing Request Class

on:
    pull_request: null

jobs:
    missing_request_class:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0

            -   uses: "ramsey/composer-install@v1"

            -   run: vendor/bin/rector process src --ansi